using Godot;
using System;

public partial class Genome : Node
{

	public enum GENE_ATTRIBUTES {
		DEPTH, 
		SCALE, SCALE_VARIATION, SCALE_LAYER_MODIFIER,
		COLOR_R, COLOR_G, COLOR_B, COLOR_VARIATION_RANGE,
		NODES_RANGE_MIN, NODES_RANGE_MAX, NODES_LAYER_MODIFIER,
		ANGLE_RANGE_MIN, ANGLE_RANGE_MAX, ANGLE_LAYER_MODIFIER,
		POLYGON_RADIUS_RANGE_MIN, POLYGON_RADIUS_RANGE_MAX,
		POLYGON_SIDES_RANGE_MIN, POLYGON_SIDES_RANGE_MAX,
		SYMMETRICAL
	}

}
